### ISSUE TITLE
[BUG]org.opensearch.performanceanalyzer.collectors.CacheConfigMetricsCollector$CacheMaxSizeStatus

### ISSUE THREAD

**Issue by coredump17** [opensearch-project/performance-analyzer#644]
**What is the bug?**
Since upgrading from 2.12 to 2.13 i see the below WARN messages spamming the logs
Json Mapping Error: Cannot invoke “java.lang.Long.longValue()” because “this.cacheMaxSize” is null (through reference chain: org.opensearch.performanceanalyzer.collectors.CacheConfigMetricsCollector$CacheMaxSizeStatus[“Cache_MaxSize”])

**How can one reproduce the bug?**
install 2.13

**What is the expected behavior?**
no errors logged

**What is your host/environment?**
opensearch 2.13 container

**Comment by timolow** [comment]
Having this issue too.

**Comment by guldil** [comment]
Same here.

**Comment by sarankup** [comment]
Same here

**Comment by Gradlon** [comment]
Same here.

**Comment by ComBin** [comment]
Me too

**Comment by dxturner** [comment]
see this also.

**Comment by slayerjk** [comment]
same here

**Comment by rtista** [comment]
Same here on after update from 2.12.0 to 2.13.0.

**Comment by 22charud** [comment]
I have the same issue on 2.13

**Comment by pmarjou22** [comment]
same here

**Comment by tdankers** [comment]
Same here :-(

**Comment by merlinz01** [comment]
Same here, Version 2.13.0 on Debian 12. Is there perhaps a setting that needs to be set?

**Comment by merlinz01** [comment]
I upgraded back to 2.13.0 and [removed the Performance Analyzer plugin](https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer), and the errors aren't appearing for me.

Seems to be related to JSON marshaling/unmarshaling of a performance metric perhaps?

v1.13.0
https://github.com/opensearch-project/performance-analyzer/blob/42889919319fb0a1f89c6e07b58cd9f7ee2d8718/src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java#L113-L114

main
https://github.com/opensearch-project/performance-analyzer/blob/4928231bed654a6d14c3d27668e1e50e29280a38/src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java#L145-L146

**Comment by cinhtau** [comment]
I just disable the Performance Analyzer on 2.14 today as described in https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer.

**Comment by ansjcy** [comment]
There are some exceptions raised in the [collectMetrics function](https://github.com/opensearch-project/performance-analyzer/blame/2.13/src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java#L73) in CacheConfigMetricsCollector. The current logic [returns a CacheMaxSizeStatus](https://github.com/opensearch-project/performance-analyzer/blame/e34588a244d7ba3f5e839829ab90cef00f577ae8/src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java#L91) with null cacheMaxSize if exception is raised, while we require it [to be non-null](https://github.com/opensearch-project/performance-analyzer/blame/2.13/src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java#L146).

@varunsrivathsav, @atharvasharma61, @psychbot,  let's investigate this future to understand:
- What is causing the error to be thrown in 2.13? 
- We should fix the above bug in the code to raise/log the exception, rather than return an Object with null value.

**Comment by caothu159** [comment]
While waiting for the new upgrade, you can perform the following fixes:
In `debian` or `ubuntu`, make `opensearch.service` auto restart on fail, crash or has an unclean exit:
- Edit service file, example `/lib/systemd/system/opensearch.service`
- In `[Service]` before `[Install]`, add 2 lines:
```
Restart=on-failure
RestartSec=60s
```

Example results:
```
...
# Allow a slow startup before the systemd notifier module kicks in to extend the timeout
TimeoutStartSec=75

Restart=on-failure
RestartSec=60s

[Install]
WantedBy=multi-user.target
...
```

**Comment by borisdenis** [comment]
same here
