### ISSUE TITLE
[BUG] Opensearch 1.1.0 ShardBulkDocs Metrics is always empty

### ISSUE THREAD

**Issue by pmarjou22** [opensearch-project/performance-analyzer#77]
**What is the bug?**
ShardBulkDocs Metrics is always empty when calling performance Analyzer API. Other metrics are working.

**How can one reproduce the bug?**
1. docker compose enclosed
[docker-compose.txt](https://github.com/opensearch-project/performance-analyzer/files/7434148/docker-compose.txt)
2. Follow step to activate performance analyzer  : https://opensearch.org/docs/latest/opensearch/install/docker/#optional-set-up-performance-analyzer 
3. Create test  index and POST documents in this index PUT test  (see enclosed)
[postdata.txt](https://github.com/opensearch-project/performance-analyzer/files/7434154/postdata.txt)
4. while pushing documents, call from your browser : http://localhost:9600/_plugins/_performanceanalyzer/metrics?metrics=ShardBulkDocs,ShardEvents&agg=sum,sum 
 you 'll get only ShardEvents numbers and no data on ShardBulkDocs

    `{"CkXsbxtMTDisNx2ahHqrIw": {"timestamp": 1635425175000, "data": {"fields":[{"name":"ShardBulkDocs","type":"DOUBLE"},{"name":"ShardEvents","type":"DOUBLE"}],"records":[[0.0,27.0]]}}}`

**What is the expected behavior?**
On previous Open Distro 1.13.1 this call was working

**What is your host/environment?**
 - Opensearch 1.1.0 Docker

**Comment by pmarjou22** [comment]
I investigated and found out that there are no more metrics from operation : "shardbulk" available from the API

**Comment by pmarjou22** [comment]
we have upgraded to 1.2.0, the bug is still here

**Comment by systemosyn** [comment]
I face a similar issue somehow with have an opensearch cluster of two nodes, (1 hot and 1 warm), and the shardbulkdocs that we received were always equals to 0, receiving only the shardfetch and sharquery operation (there was no shardbulk operation). when I look into the eventLog files, I see the issue, which is that only the shabulk started event are written, i was not able to see a single finish event over a shardbulk operation:
   
[1667494070000.txt](https://github.com/opensearch-project/performance-analyzer/files/9979213/1667494070000.txt)
[1667494060000.txt](https://github.com/opensearch-project/performance-analyzer/files/9979214/1667494060000.txt)
[1667494065000.txt](https://github.com/opensearch-project/performance-analyzer/files/9979215/1667494065000.txt)

As an ugly quick fix I manage to patch my rca agent, by removing the WHERE clause that filter events when they are not finished, but it does not solve the root cause at all. 

@kkhatua @sruti1312 , Do you have any suggestion to help me to investigate this issue please? Don't hesitate if you need more information.
